reports/urls.py
from django.urls import path
from .views import (report_form_view,
                    ReportListView,
                    report_detail_view,
                    render_pdf_view,
                    UploadTemplateView,
                    csv_upload_view)

app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name='main'),
    path('save/', report_form_view, name='create-report'),
    path('upload/', csv_upload_view, name='upload'),
    path('from-file/', UploadTemplateView.as_view(), name='from-file'),
    path('pdf/<pk>', render_pdf_view, name='pdf'),
    path('<pk>/', report_detail_view, name='detail'),
]

sales/urls.py
from django.urls import path
from .views import (
    home_view,
    SalesListView,
    sales_detail_view
)

app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home'),
    path('sales/', SalesListView.as_view(), name='list'),
    path('sales/<pk>', sales_detail_view, name='detail'),
]

sales_reports/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/models.py
from django.db import models
from profiles.models import Profile
from django.urls import reverse


class Report(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='reports', blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ('-created',)

reports/forms.py
from django import forms
from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'remarks')

reports/views.py
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from xhtml2pdf import pisa

from profiles.models import Profile
from django.http import JsonResponse, HttpResponse
from .utils import get_report_image
from .models import Report
from django.views.generic import ListView, TemplateView
from django.utils.dateparse import parse_date
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from sales.models import Sale, Position, CSV
from products.models import Product
from customers.models import Customer

import csv


class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'report/main.html'


@login_required
def report_detail_view(request, pk):
    qs = Report.objects.get(id=pk)
    context = {
        'qs': qs,
    }
    return render(request, 'report/detail.html', context=context)


@login_required
def report_form_view(request):
    if request.is_ajax():
        name = request.POST.get('name')
        remarks = request.POST.get('remarks')
        image = request.POST.get('image')
        author = Profile.objects.get(user=request.user)

        img = get_report_image(image)

        Report.objects.create(name=name, remarks=remarks, author=author, image=img)

        return JsonResponse({'msg': 'Report created'})
    return JsonResponse({'msg': 'Error Occurred'})


@login_required
def render_pdf_view(request, pk):
    template_path = 'report/pdf.html'
    context = {'pdf_object': get_object_or_404(Report, pk=pk)}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response


class UploadTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'report/from_file.html'


@login_required
def csv_upload_view(request):
    if request.method == 'POST':
        csv_file_name = request.FILES.get('file').name
        csv_file = request.FILES.get('file')
        obj, created = CSV.objects.get_or_create(file_name=csv_file_name)
        if created:
            obj.csv_file = csv_file
            obj.save()
            with open(obj.csv_file.path, 'r') as f:
                reader = csv.reader(f)
                reader.__next__()
                for row in reader:
                    # print(row)
                    transaction_id = row[1]
                    product = row[2]
                    quantity = int(row[3])
                    customer = row[4]
                    created = parse_date(row[5])

                    try:
                        product_obj = Product.objects.get(name__iexact=product)
                    except Product.DoesNotExist:
                        product_obj = None
                    if product_obj is not None:
                        customer_obj, _ = Customer.objects.get_or_create(name=customer)
                        salesman_obj = Profile.objects.get(user=request.user)
                        position_obj = Position.objects.create(product=product_obj, quantity=quantity, created=created)

                        sale_obj, _ = Sale.objects.get_or_create(transaction_id=transaction_id, customer=customer_obj,
                                                                 salesman=salesman_obj, created=created)
                        sale_obj.positions.add(position_obj)
                        sale_obj.save()
                return JsonResponse({'file_upload': True})
        return JsonResponse({'file_upload': False})
    return HttpResponse()

reports/templates/report/detail.html
{% extends 'base.html' %}
{% block title %}
{{ qs.name }} Details
{% endblock title %}

{% block content %}
    <h1>{{ qs.name }}</h1>
    {% if qs.image %}
        <img src="{{ qs.image.url }}" alt="{{ qs.name }}" class="img-fluid">
    {% endif %}
    <br/>
    <h3>Remarks</h3>
    <p>{{ qs.remarks }}</p>
    <hr/>
    <p>Author: <b>{{ qs.author.user.username }}</b></p>
    <p>Created: <b>{{ qs.created }}</b></p>
{% endblock content %}

reports/templates/report/from_file.html
{% extends 'base.html' %}
{% load static %}
{% block scripts %}
    <script src="{% static 'report/upload.js' %}" defer></script>
{% endblock scripts %}
{% block title %}
    Upload Sales File
{% endblock title %}

{% block content %}
    <h4>Upload Sales File</h4>
    <hr/>
    <div id="alert-box"></div>
    <form class="dropzone" id="dropzone-form">
        {% csrf_token %}
        <div class="fallback">
            <input name="file" type="file" multiple/>
        </div>
    </form>
{% endblock content %}

reports/templates/report/main.html
{% extends 'base.html' %}
{% block title %}
    Report List
{% endblock title %}

{% block content %}
    {% for obj in object_list %}

        <div class="card mb-3">
            {% if obj.image %}
                <img src="{{ obj.image.url }}" class="card-img-top" alt="{{ obj.name }}">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ obj.name }}</h5>
                <p class="card-text">{{ obj.remarks|truncatewords:20 }}</p>
                <a href="{{ obj.get_absolute_url }}" class="btn btn-primary">Details</a>
                <a href="{% url 'reports:pdf' pk=obj.id %}" class="btn btn-danger">PDF</a>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

reports/templates/report/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PDF {{ pdf_object.name }}</title>
    <style>
        .image {
            width: 100%;
            height: auto;
        }
    </style>
</head>
<body>
<h1>{{ pdf_object.name }}</h1>
    {% if pdf_object.image %}
        <img src="{{ pdf_object.image.path }}" alt="{{ pdf_object.name }}">
    {% endif %}
    <br/>
    <h3>Remarks</h3>
    <p>{{ pdf_object.remarks }}</p>
    <hr/>
    <p>Author: <b>{{ pdf_object.author.user.username }}</b></p>
    <p>Created: <b>{{ pdf_object.created }}</b></p>
</body>
</html>